import Head from 'next/head'
import { BalanceHeader } from '@/components/screen1/balanceheader'
import { ScrollingBnts } from '@/components/screen1/scrollingbuttons'
import { NftCards } from '@/components/screen1/nftcards'
import { nft_data } from './api/nft_data'
export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto-NFT-App</title>
        <meta name="description" content="Crypto-NFT-App Generated by Gideon " />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       <BalanceHeader />
       <ul className="scroll">
          <ScrollingBnts />
          <NftCards data={nft_data} />
       </ul>
      </main>
    </>
  )
}
